name: Deployment to GitHub Pages
on:
  push:
    branches: [ zoomi ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true
  NEXT_TELEMETRY_DISABLED: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup Environment
        run: |
          npm install -g yarn
          yarn install
      - name: validate members
        run: |
          yarn cmd members.validate
      - name: Generate build
        run: |
          yarn build
      - name: Deploy to GitHub Pages
        run: |
          git config user.email "zoomi.raja@gmail.com"
          git config user.name "zoomi-raja"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
